# Generated by Django 3.2 on 2023-01-25 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
