# Generated by Django 3.2 on 2023-01-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='write titles name', max_length=256, verbose_name='titles name')),
                ('year', models.DateField(auto_now_add=True, verbose_name='titles year')),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='title/', verbose_name='image')),
                ('category', models.ForeignKey(blank=True, help_text='CategoryTitle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='reviews.category', verbose_name='category')),
                ('genre', models.ManyToManyField(blank=True, help_text='GenreTitle', null=True, related_name='title', to='reviews.Genre', verbose_name='genre')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'titles',
            },
        ),
    ]
